### PR TITLE
Fix useless delays

### PR DESCRIPTION
**Pull request by SSebigo**
I added linting for code consistency across the entire codebase (see "lint"  in pubspec.yaml and analysis_options.yaml).

I also updated all files that needed an update to comply with the linter.

I saw many inconsistencies in the codebase (I haven't fix them, took to much time just to comply with the linter).

The app is really slow when navigating from screens to screens, must be because of the api call but you should navigate first and make the api call then. It makes the transition look smoother that way.

### CODE REVIEW

**Comment by SSebigo** [comment]
Updated details_by_id, I had removed a portion of the code that was necessary so I put it back

**Comment by febryardiansyah** [comment]
thank you so much, i appreciate it 👍!! as you said, the app is really slow when navigating from screens to screens. i realized it too, if i call api every time user moves to other screen. doesn't it kinda annoying ? or do u know how to make if the data has already loaded then bloc not triggering event again ?

**Comment by febryardiansyah** [comment]
there are some issues when i tried to run the app from your pull request repo

**1. search anime by name**
`E/flutter ( 8776): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: type 'int' is not a subtype of type 'double' in type cast
E/flutter ( 8776): #0      new SearchModelResult.fromMap (package:animku/models/search_model_results.dart:42:28)
E/flutter ( 8776): #1      new Results.fromMap.<anonymous closure> (package:animku/models/search_model_results.dart:12:39)
E/flutter ( 8776): #2      MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
E/flutter ( 8776): #3      ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
E/flutter ( 8776): #4      new List.from (dart:core-patch/array_patch.dart:57:19)
E/flutter ( 8776): #5      new Results.fromMap (package:animku/models/search_model_results.dart:10:26)`

**2. Youtube webview in detail by id (when data is null)**
`The following assertion was thrown building YoutubeWebView(dirty, state: _YoutubeWebViewState#779d0):
A non-null String must be provided to a Text widget.
'package:flutter/src/widgets/text.dart':
Failed assertion: line 298 pos 10: 'data != null'`

**3. Schedule Screen**
`type MappedListIterable<dynamic,dynamic> is not subtype of type List<AnimeList> in type cast`

I think it because you've added cast in class model 👍

**Comment by SSebigo** [comment]
Type casting is quite annoying but not declaring types even more.
I'll fix these asap, it shouldn't be that hard 🤔.

And for api calls, maybe you can alleviate the charge by paginating. So you load ten items first and then when the user scroll you load ten more, etc... I don't know if it's possible with Jikan but it's the only solution I can think of rn.

**Comment by SSebigo** [comment]
Unable to reproduce:

**2. Youtube webview in detail by id (when data is null)**
``
The following assertion was thrown building YoutubeWebView(dirty, state: _YoutubeWebViewState#779d0): A non-null String must be provided to a Text widget. 'package:flutter/src/widgets/text.dart': Failed assertion: line 298 pos 10: 'data != null'
``
Which anime did you press on to get this error?

**Comment by febryardiansyah** [comment]
jikan api just provide routes as myanimelist does, so only some routes provide pagnation. in my case which is current season endpoint doesn't support it. i was thingking to do lazyloading/infinitelist as you said before

for youtube webview issue, i got that error when try to see anime "Maou Gakuin no Futekigousha" in summer season

**Comment by SSebigo** [comment]
All the errors above should be fixed:

**1. search anime by name**:
I just cast score type to num instead of int or double, since it seems that you can have both and neither can be cast to the other

**2. Youtube webview in detail by id (when data is null)**
just added an if condition to only  show the button when trailerUrl is not null
I had to update the Dart sdk from 2.10 >= <. 3.0.0 to 2.6.0 >= <= 3.0.0 to enable flow control inside list widgets

**3. Schedule Screen**
Just rewrote type cast using cast() keyword + as List when decoding the response body[day]

**Pull request merged**
